### ISSUE TITLE
Missing File.

### ISSUE THREAD

**Issue by geetanshsaini** [steveshambles/The-Poker-Machine#1]
I stumbled upon your blog and found the project pretty interesting. So I went ahead and downloaded it from github but there seems to be a missing file mentioned in the code. This is the error I get when trying to load the "poker-machine-v1-2.py" - 

```
Traceback (most recent call last):
  File "poker-machine-v1-2.py", line 116, in <module>
    logo_result_frame()
  File "poker-machine-v1-2.py", line 110, in logo_result_frame
    PHOTO = PhotoImage(file=r'cards/result-frame.png')
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 4061, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 4006, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "cards/result-frame.png": no such file or directory
```

I checked the cards folder manually and there's no file named "result-frame.png".

The specific function is the logo_result_frame() function on line 107.

**Comment by steveshambles** [comment]
Hi myfriend
I'm sorry I messed up the github, I will fix it soon as I can. In the mean time please get your files here for V1.2.
http://www.mediafire.com/file/cblkr0v2te9httr/Poker-Machine-V1-2-src-win-exe.zip/file

Please let me know if there is still an issue. As you are using Python V3.8 there may be some issues. I was using V3.65 at the time, though should be compatible, not all libraries are converted to work on V3.8 yet.

Cheers.
Steve

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by steveshambles** [comment]
Missing files fixed.
